apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airports-app
  namespace: airports
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airports-app
    spec:
      containers:
      - name: airports-app
        image: bihanc/airport:latest
        ports:
        - containerPort: 8080
        livenessProbe:
         httpGet:
          path: /health/live
          port: 8080
          httpHeaders:
          - name: X-Custom-Header
            value: Awesome
         initialDelaySeconds: 15
         timeoutSeconds: 10
        readinessProbe:
         httpGet:
          path: /health/ready
          port: 8080
          httpHeaders:
          - name: X-Custom-Header
            value: Awesome
         initialDelaySeconds: 5
         timeoutSeconds: 10
         periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: airports-app
  namespace: airports
  labels:
    app: airports-app
spec:
  ports:
  - port: 8000
    targetPort: 8080
  selector:
    app: airports-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: airports.test.com
    http:
      paths:
      - path: /airports
        backend:
          serviceName: airports-app
          servicePort: 8000


